"""
Font Forensics Module
Analyzes font consistency within PDFs to detect manual tampering.
Bank-generated PDFs use consistent proprietary fonts; edited documents show mixed consumer fonts.
"""

import fitz  # PyMuPDF
from collections import Counter
from typing import List, Dict, Any
from models.domain import AnomalyFeature


def analyze_font_consistency(file_path: str) -> List[AnomalyFeature]:
    """
    Analyzes font usage across all pages of a PDF.
    Flags documents with too many distinct font families or suspicious consumer fonts.
    """
    anomalies = []

    try:
        doc = fitz.open(file_path)
        all_fonts: List[str] = []
        all_sizes: List[float] = []
        font_page_map: Dict[str, List[int]] = {}

        for page_num in range(len(doc)):
            page = doc[page_num]
            blocks = page.get_text("dict", flags=fitz.TEXT_PRESERVE_WHITESPACE)

            for block in blocks.get("blocks", []):
                if block.get("type") != 0:  # text blocks only
                    continue
                for line in block.get("lines", []):
                    for span in line.get("spans", []):
                        font_name = span.get("font", "unknown").lower()
                        font_size = span.get("size", 0)

                        all_fonts.append(font_name)
                        all_sizes.append(font_size)

                        if font_name not in font_page_map:
                            font_page_map[font_name] = []
                        font_page_map[font_name].append(page_num + 1)

        doc.close()

        if not all_fonts:
            return anomalies

        # --- Check 1: Too many distinct font families ---
        # Normalize font names to base families
        base_families = set()
        for font in all_fonts:
            # Strip common suffixes like -bold, -italic, etc.
            base = font.split("-")[0].split(",")[0].strip()
            base_families.add(base)

        if len(base_families) > 4:
            anomalies.append(AnomalyFeature(
                type="Font Inconsistency",
                description=(
                    f"Document uses {len(base_families)} distinct font families: "
                    f"{', '.join(sorted(list(base_families))[:6])}. "
                    "Bank-generated statements typically use 1-2 consistent fonts. "
                    "Multiple fonts suggest manual editing or copy-paste from different sources."
                ),
                risk_level="High"
            ))

        # --- Check 2: Suspicious consumer fonts mixed with system fonts ---
        consumer_fonts = [
            "arial", "times", "calibri", "cambria", "comic",
            "georgia", "verdana", "trebuchet", "segoe", "tahoma",
            "impact", "palatino", "garamond", "bookman"
        ]
        proprietary_indicators = [
            "courier", "ocr", "micr", "bank", "monospace",
            "code", "consolas", "lucida", "fixed"
        ]

        found_consumer = []
        found_proprietary = []
        for base in base_families:
            if any(cf in base for cf in consumer_fonts):
                found_consumer.append(base)
            if any(pf in base for pf in proprietary_indicators):
                found_proprietary.append(base)

        if found_consumer and found_proprietary:
            anomalies.append(AnomalyFeature(
                type="Mixed Font Origin",
                description=(
                    f"Document mixes proprietary/monospace fonts ({', '.join(found_proprietary)}) "
                    f"with consumer fonts ({', '.join(found_consumer)}). "
                    "This pattern is common when numbers are manually replaced using standard fonts "
                    "in a document originally generated by banking software."
                ),
                risk_level="High"
            ))

        # --- Check 3: Inconsistent font sizes for numeric content ---
        font_counter = Counter(all_fonts)
        size_counter = Counter(round(s, 1) for s in all_sizes)

        # If the document has a dominant size but some text in a very different size
        if len(size_counter) > 1:
            most_common_size = size_counter.most_common(1)[0][0]
            outlier_sizes = [s for s, c in size_counter.items()
                          if abs(s - most_common_size) > 2.0 and c < len(all_sizes) * 0.05]
            if outlier_sizes:
                anomalies.append(AnomalyFeature(
                    type="Font Size Anomaly",
                    description=(
                        f"Dominant text size is {most_common_size}pt but found small clusters of text at "
                        f"{', '.join(str(s) + 'pt' for s in outlier_sizes[:3])}. "
                        "Inserted or replaced text often has slightly different sizing than the original."
                    ),
                    risk_level="Low"
                ))

    except Exception as e:
        anomalies.append(AnomalyFeature(
            type="Font Analysis Error",
            description=f"Could not analyze fonts: {str(e)}",
            risk_level="Low"
        ))

    return anomalies
