from typing import Dict, Any, List

try:
    import fitz
    PYMUPDF_AVAILABLE = True
except ImportError:
    PYMUPDF_AVAILABLE = False

class SignatureValidator:
    """
    Checks for digital signatures in PDFs.
    """
    def validate(self, pdf_bytes: bytes, classification: str = "Unknown") -> List[Dict[str, Any]]:
        findings = []
        if not PYMUPDF_AVAILABLE:
            return findings

        try:
            has_signature = False
            doc = fitz.open(stream=pdf_bytes, filetype="pdf")

            # 1. Check for PyMuPDF widget types
            for page_num in range(len(doc)):
                page = doc[page_num]
                widgets = page.widgets()
                if widgets:
                    for widget in widgets:
                        if widget.field_type == fitz.PDF_WIDGET_TYPE_SIGNATURE:
                            has_signature = True
                            break

            # 2. String lookup fallback
            if b"/ByteRange" in pdf_bytes and b"/Contents" in pdf_bytes and b"/Type /Sig" in pdf_bytes:
                has_signature = True

            doc.close()

            # Bank statements and Payslips SHOULD have signatures
            if not has_signature and classification in ["Bank Statement", "Payslip"]:
                findings.append({
                    "name": "Missing Digital Signature",
                    "severity": "HIGH",
                    "description": f"Authentic {classification.lower()}s generated by modern software carry digital cryptographic signatures. None were found.",
                    "evidence": ["No /Sig or /ByteRange blocks detected in PDF structure."]
                })

            # Even if it has a signature, if it has incremental updates after it, it might be tampered, but we handle updates in pdf_analyzer.

            return findings
        except Exception as e:
            print(f"[SignatureValidator] Error: {e}")
            return findings

signature_validator = SignatureValidator()
