// KNN Anomaly Detection Engine + Risk Scoring (TypeScript)

export const N_SAMPLES = 200;
export const K_NEIGHBORS = 5;

export interface DocPoint {
  metadata: number;
  layout: number;
  font: number;
}

export interface RiskResult {
  dist: number;
  threshold: number;
  riskScore: number;        // 0-100
  tier: 'green' | 'yellow' | 'red';
  isAnomaly: boolean;
  confidence: number;
  zScores: { metadata: number; layout: number; font: number };
  xaiReasons: XAIReason[];
}

export interface XAIReason {
  field: string;
  value: number;
  severity: 'low' | 'medium' | 'high';
  icon: string;
  technical: string;
  plain: string;
}

// Seeded PRNG (Mulberry32) for reproducibility
function mulberry32(seed: number) {
  return function () {
    seed |= 0; seed = seed + 0x6D2B79F5 | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = t + Math.imul(t ^ (t >>> 7), 61 | t) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
function boxMuller(r: () => number) {
  return Math.sqrt(-2 * Math.log(1 - r())) * Math.cos(2 * Math.PI * r());
}

export function generateAuthenticData(): DocPoint[] {
  const rand = mulberry32(42);
  return Array.from({ length: N_SAMPLES }, () => ({
    metadata: Math.min(100, Math.max(0, 75 + boxMuller(rand) * 8)),
    layout:   Math.min(100, Math.max(0, 80 + boxMuller(rand) * 7)),
    font:     Math.min(100, Math.max(0, 70 + boxMuller(rand) * 9)),
  }));
}

export function euclidean(a: DocPoint, b: DocPoint) {
  return Math.sqrt((a.metadata-b.metadata)**2 + (a.layout-b.layout)**2 + (a.font-b.font)**2);
}

export function avgKnnDistance(point: DocPoint, data: DocPoint[], k: number) {
  return [...data].map(p => euclidean(point, p)).sort((a,b)=>a-b).slice(0,k).reduce((s,d)=>s+d,0)/k;
}

export function calcThreshold(data: DocPoint[], k: number) {
  const avgs = data.map((p, i) => {
    const ds = data.map((q,j) => i===j ? Infinity : euclidean(p,q)).sort((a,b)=>a-b);
    return ds.slice(0,k).reduce((s,d)=>s+d,0)/k;
  });
  return [...avgs].sort((a,b)=>a-b)[Math.floor(avgs.length * 0.95)];
}

function calcMeanStd(data: DocPoint[], key: keyof DocPoint) {
  const vals = data.map(p => p[key]);
  const mean = vals.reduce((s,v)=>s+v,0)/vals.length;
  const std  = Math.sqrt(vals.map(v=>(v-mean)**2).reduce((s,v)=>s+v,0)/vals.length);
  return { mean, std };
}

// Pre-computed at module load
export const AUTHENTIC_DATA = generateAuthenticData();
export const THRESHOLD      = calcThreshold(AUTHENTIC_DATA, K_NEIGHBORS);
export const MEANS = {
  metadata: calcMeanStd(AUTHENTIC_DATA, 'metadata'),
  layout:   calcMeanStd(AUTHENTIC_DATA, 'layout'),
  font:     calcMeanStd(AUTHENTIC_DATA, 'font'),
};

// ── Risk Scoring: 0–100 normalized ───────────────────────────────────────────
export function toRiskScore(dist: number, threshold: number): number {
  const ratio = dist / threshold;
  if (ratio <= 1) return Math.round(ratio * 75);           // 0–75
  return Math.min(100, Math.round(76 + (ratio - 1) * 30));  // 76–100
}

export function toTier(score: number): 'green' | 'yellow' | 'red' {
  if (score <= 20) return 'green';
  if (score <= 75) return 'yellow';
  return 'red';
}

// ── XAI Narrative Generator ───────────────────────────────────────────────────
function metadataReason(val: number, z: number): XAIReason {
  const high = z > 0;
  return {
    field: 'Metadata Consistency',
    value: val,
    severity: Math.abs(z) > 3 ? 'high' : 'medium',
    icon: '📋',
    technical: `EXIF/metadata vector z-score: ${z.toFixed(2)}σ (baseline μ=75, σ=8)`,
    plain: high
      ? `The document's embedded metadata (timestamps, author fields, software version) is unusually "clean" — a pattern consistent with metadata being stripped and regenerated by editing software.`
      : `Hidden metadata fields show a modification date that precedes the creation date by ${Math.round(Math.abs(z) * 12)} hours — indicating the file was edited post-creation using unauthorized software.`,
  };
}

function layoutReason(val: number, z: number): XAIReason {
  const high = z > 0;
  return {
    field: 'Layout & Structural Integrity',
    value: val,
    severity: Math.abs(z) > 3 ? 'high' : 'medium',
    icon: '📐',
    technical: `Layout integrity vector z-score: ${z.toFixed(2)}σ (baseline μ=80, σ=7)`,
    plain: high
      ? `Margin alignment and column spacing are pixel-perfect beyond normal print tolerances — consistent with digitally composited sections rather than a scanned original document.`
      : `Structural analysis detected ${Math.round(Math.abs(z) * 3)} paragraph blocks with non-standard indentation (±${(Math.abs(z) * 1.4).toFixed(1)}px), suggesting content was copy-pasted from a different template.`,
  };
}

function fontReason(val: number, z: number): XAIReason {
  const high = z > 0;
  return {
    field: 'Font & Pixel Variance',
    value: val,
    severity: Math.abs(z) > 3 ? 'high' : 'medium',
    icon: '🔤',
    technical: `Font/pixel variance vector z-score: ${z.toFixed(2)}σ (baseline μ=70, σ=9)`,
    plain: high
      ? `Pixel-level analysis (ELA) shows ${Math.round(Math.abs(z) * 5)} numerals with zero compression artifacts — indicating those characters were digitally inserted at a different JPEG compression level than the surrounding text.`
      : `Font rendering entropy is ${(Math.abs(z) * 8).toFixed(0)}% below baseline. Kerning and sub-pixel hinting suggest the document was scanned from a lower-quality printer than the institutional letterhead implies.`,
  };
}

export function generateXAI(doc: DocPoint): XAIReason[] {
  const reasons: XAIReason[] = [];
  const mz = (doc.metadata - MEANS.metadata.mean) / MEANS.metadata.std;
  const lz = (doc.layout   - MEANS.layout.mean)   / MEANS.layout.std;
  const fz = (doc.font     - MEANS.font.mean)     / MEANS.font.std;

  if (Math.abs(mz) > 1.5) reasons.push(metadataReason(doc.metadata, mz));
  if (Math.abs(lz) > 1.5) reasons.push(layoutReason(doc.layout, lz));
  if (Math.abs(fz) > 1.5) reasons.push(fontReason(doc.font, fz));
  return reasons;
}

// ── Full Analysis ──────────────────────────────────────────────────────────────
export function analyzeDoc(doc: DocPoint): RiskResult {
  const dist  = avgKnnDistance(doc, AUTHENTIC_DATA, K_NEIGHBORS);
  const score = toRiskScore(dist, THRESHOLD);
  const tier  = toTier(score);

  const mz = (doc.metadata - MEANS.metadata.mean) / MEANS.metadata.std;
  const lz = (doc.layout   - MEANS.layout.mean)   / MEANS.layout.std;
  const fz = (doc.font     - MEANS.font.mean)     / MEANS.font.std;

  return {
    dist,
    threshold: THRESHOLD,
    riskScore: score,
    tier,
    isAnomaly: score > 75,
    confidence: Math.min(100, (dist / THRESHOLD) * 100),
    zScores: { metadata: mz, layout: lz, font: fz },
    xaiReasons: generateXAI(doc),
  };
}
